- name: demo on variables
  hosts: localhost
  vars:
    url: Dakati.com
  tasks:
    - name: printing url variable( declaring variable on play level)
      ansible.builtin.debug:
        msg: "{{ url }}"
- name: demo on variables but at task level
  hosts: localhost
  tasks:
    - name: printing url1 variable at task level
      ansible.builtin.debug:
        msg: "{{ url1 }}"
      vars:
        url1: Dakati.com














