- name: demo on variables
  hosts: localhost
  vars:
    url: Dakati.com
  tasks:
    - name: printing url variable( declaring variable on play level)
      ansible.builtin.debug:
        msg: "{{ url }}"
      vars:
        url: Bharath.com
- name: demo on variables but at task level
  hosts: localhost
  vars:
    url1: Bharath.com
    url2: Bharath.com
  tasks:
    - name: printing url1 variable at task level
      ansible.builtin.debug:
        msg: "{{ url1 }}"
      vars:
        url1: Dakati.com
    - name: printing url2 variable at task level
      ansible.builtin.debug:
        msg: "{{ url2 }}"
      vars:
        url2: Dakati.com

- name: Register variable
  hosts: localhost
  tasks:
    - name: getting uptime of system
      ansible.builtin.shell: uptime
      Register: out
    - name: storing out variable
      ansible.builtin.debug:
        msg: "{{out}}"



















