- name: demo on variables
  hosts: localhost
  vars:
    url: Dakati.com
  tasks:
    - name: printing url variable( declaring variable on play level)
      ansible.builtin.debug:
        msg: "{{url}}"





