- name: demo on loops
  hosts: localhost
  tasks:
    - name: printing loops
      ansible.builtin.debug:
        msg: fruits is {{ item }}
      loop:
        - apple
        - banana
        - kiwi


- name: demo on loops declaring at play level
  hosts: localhost
  vars:
    fruits:
      - apple
      - banana
      - kiwi
  tasks:
    - name: printing loop
      ansible.builtin.debug:
        msg: fruit is {{ item }}
      loop: "{{ fruits }}"




