- name: demo on loops
  hosts: localhost
  tasks:
    - name: printing loops
      ansible.builtin.debug:
        msg: fruits is {{ item }}
      loop:
        - apple
        - banana
        - kiwi


- name: printing loops at play level
  hosts: localhost
  vars:
    fruits:
      - apple
      - banana
      - kiwi
  tasks:
    - name: printing loop
      ansible.builtin.debug:
        msg: fruit is {{ item }}
      loop: "{{fruits}}"


- name: printing loops using map
  hosts: localhost
  tasks:
    - name: printing loops
      ansible.builtin.debug:
        msg: fruit is {{ item.name }} , {{ item.quantity}}
      loop:
        - {name: apple , quantity: 100}
        - {name: banana , quantity: 200}
        - {name: kiwi, quantity: 300}



