- name: demo on loops
  hosts: localhost
  tasks:
    - name: printing loops
      ansible.builtin.debug:
        msg: fruits is {{ item }}
      loop:
        - apple
        - banana
        - kiwi







